
#------------------------会员管理(目录)---------------------------
['会员管理']
menuId = 3000
icon = 'product'
path = 'peoples'

#------------------------会员管理.学校管理(二级菜单)---------------------------
['会员管理'.'学校管理']
menuId = 3001
icon = 'product-list'
path = 'managementSchools'

#-----------会员管理学校管理 按钮权限------------
['会员管理'.'学校管理'.'按钮权限'.'查询']
menuId = 3002
perms = 'query'

['会员管理'.'学校管理'.'按钮权限'.'添加']
menuId = 3003
perms = 'add'

['会员管理'.'学校管理'.'按钮权限'.'编辑']
menuId = 3004
perms = 'edit'

['会员管理'.'学校管理'.'按钮权限'.'删除']
menuId = 3005
perms = 'remove'

['会员管理'.'学校管理'.'按钮权限'.'导入']
menuId = 3006
perms = 'import'

['会员管理'.'学校管理'.'按钮权限'.'导出']
menuId = 3007
perms = 'export'


#------------------------会员管理.班级管理(二级菜单)---------------------------
['会员管理'.'班级管理']
menuId = 3008
icon = 'product-list'
path = 'managementClasses'

#-----------会员管理班级管理 按钮权限------------
['会员管理'.'班级管理'.'按钮权限'.'查询']
menuId = 3009
perms = 'query'

['会员管理'.'班级管理'.'按钮权限'.'添加']
menuId = 3010
perms = 'add'

['会员管理'.'班级管理'.'按钮权限'.'编辑']
menuId = 3011
perms = 'edit'

['会员管理'.'班级管理'.'按钮权限'.'删除']
menuId = 3012
perms = 'remove'

['会员管理'.'班级管理'.'按钮权限'.'导入']
menuId = 3013
perms = 'import'

['会员管理'.'班级管理'.'按钮权限'.'导出']
menuId = 3014
perms = 'export'



#------------------------会员管理.学生管理(二级菜单)---------------------------
['会员管理'.'学生管理']
menuId = 3015
icon = 'product-list'
path = 'managementStudents'

#-----------会员管理学生管理 按钮权限------------
['会员管理'.'学生管理'.'按钮权限'.'查询']
menuId = 3016
perms = 'query'

['会员管理'.'学生管理'.'按钮权限'.'添加']
menuId = 3017
perms = 'add'

['会员管理'.'学生管理'.'按钮权限'.'编辑']
menuId = 3018
perms = 'edit'

['会员管理'.'学生管理'.'按钮权限'.'删除']
menuId = 3019
perms = 'remove'

['会员管理'.'学生管理'.'按钮权限'.'导入']
menuId = 3020
perms = 'import'

['会员管理'.'学生管理'.'按钮权限'.'导出']
menuId = 3021
perms = 'export'



#------------------------会员管理.会员管理(二级菜单)---------------------------
['会员管理'.'会员管理']
menuId = 3022
icon = 'product-list'
path = 'managementMemberships'

#-----------会员管理会员管理 按钮权限------------
['会员管理'.'会员管理'.'按钮权限'.'查询']
menuId = 3023
perms = 'query'

['会员管理'.'会员管理'.'按钮权限'.'添加']
menuId = 3024
perms = 'add'

['会员管理'.'会员管理'.'按钮权限'.'编辑']
menuId = 3025
perms = 'edit'

['会员管理'.'会员管理'.'按钮权限'.'删除']
menuId = 3026
perms = 'remove'

['会员管理'.'会员管理'.'按钮权限'.'导入']
menuId = 3027
perms = 'import'

['会员管理'.'会员管理'.'按钮权限'.'导出']
menuId = 3028
perms = 'export'


#------------------------资料管理(目录)---------------------------
['资料管理']
menuId = 3029
icon = 'upload'
path = 'material'

#------------------------资料管理.上传文件(二级菜单)---------------------------
['资料管理'.'文件网盘']
menuId = 3030
icon = 'dengji'
path = 'fileDrive'

#-----------资料管理上传文件 按钮权限------------
['资料管理'.'文件网盘'.'按钮权限'.'查询']
menuId = 3031
perms = 'query'

['资料管理'.'文件网盘'.'按钮权限'.'添加']
menuId = 3032
perms = 'add'

['资料管理'.'文件网盘'.'按钮权限'.'编辑']
menuId = 3033
perms = 'edit'

['资料管理'.'文件网盘'.'按钮权限'.'删除']
menuId = 3034
perms = 'remove'

['资料管理'.'文件网盘'.'按钮权限'.'导入']
menuId = 3035
perms = 'import'

['资料管理'.'文件网盘'.'按钮权限'.'导出']
menuId = 3036
perms = 'export'


#------------------------资料管理(目录)---------------------------
['老师管理']
menuId = 3037
icon = 'example'
path = 'teachers'



#------------------------老师管理.老师信息(二级菜单)---------------------------
['老师管理'.'老师信息']
menuId = 3038
icon = 'article'
path = 'teacherInfos'

#-----------老师管理老师信息 按钮权限------------
['老师管理'.'老师信息'.'按钮权限'.'查询']
menuId = 3039
perms = 'query'

['老师管理'.'老师信息'.'按钮权限'.'添加']
menuId = 3040
perms = 'add'

['老师管理'.'老师信息'.'按钮权限'.'编辑']
menuId = 3041
perms = 'edit'

['老师管理'.'老师信息'.'按钮权限'.'删除']
menuId = 3042
perms = 'remove'

['老师管理'.'老师信息'.'按钮权限'.'导入']
menuId = 3043
perms = 'import'

['老师管理'.'老师信息'.'按钮权限'.'导出']
menuId = 3044
perms = 'export'

